# Generated by Django 5.0.4 on 2024-04-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='name',
            field=models.CharField(default='food', max_length=20, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(default='grams', max_length=6, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='title',
            field=models.CharField(default='Best food', max_length=20, verbose_name='Title'),
        ),
    ]
